/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface VerifySignatureInterface extends utils.Interface {
  functions: {
    "getMessageHash(address,address,string,string)": FunctionFragment;
    "verifySignature(address,address,string,string,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getMessageHash" | "verifySignature"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMessageHash",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMessageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySignature",
    data: BytesLike
  ): Result;

  events: {};
}

export interface VerifySignature extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VerifySignatureInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getMessageHash(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _date: PromiseOrValue<string>,
      _ip: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    verifySignature(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _date: PromiseOrValue<string>,
      _ip: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getMessageHash(
    _from: PromiseOrValue<string>,
    _to: PromiseOrValue<string>,
    _date: PromiseOrValue<string>,
    _ip: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  verifySignature(
    _from: PromiseOrValue<string>,
    _to: PromiseOrValue<string>,
    _date: PromiseOrValue<string>,
    _ip: PromiseOrValue<string>,
    sig: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getMessageHash(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _date: PromiseOrValue<string>,
      _ip: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    verifySignature(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _date: PromiseOrValue<string>,
      _ip: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getMessageHash(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _date: PromiseOrValue<string>,
      _ip: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifySignature(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _date: PromiseOrValue<string>,
      _ip: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getMessageHash(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _date: PromiseOrValue<string>,
      _ip: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifySignature(
      _from: PromiseOrValue<string>,
      _to: PromiseOrValue<string>,
      _date: PromiseOrValue<string>,
      _ip: PromiseOrValue<string>,
      sig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
